const RISOCOLORS_PRETTY_NAMES = [
  {name: 'BLACK', pretty_name: 'Black'},
  {name: 'BURGUNDY', pretty_name: 'Burgundy'},
  {name: 'BLUE', pretty_name: 'Blue'},
  {name: 'GREEN', pretty_name: 'Green'},
  {name: 'MEDIUMBLUE', pretty_name: 'Medium Blue'},
  {name: 'BRIGHTRED', pretty_name: 'Bright Red'},
  {name: 'RISOFEDERALBLUE', pretty_name: 'Riso Federal Blue'},
  {name: 'PURPLE', pretty_name: 'Purple'},
  {name: 'TEAL', pretty_name: 'Teal'},
  {name: 'FLATGOLD', pretty_name: 'Flat Gold'},
  {name: 'HUNTERGREEN', pretty_name: 'Hunter Green'},
  {name: 'RED', pretty_name: 'Red'},
  {name: 'BROWN', pretty_name: 'Brown'},
  {name: 'YELLOW', pretty_name: 'Yellow'},
  {name: 'MARINERED', pretty_name: 'Marine Red'},
  {name: 'ORANGE', pretty_name: 'Orange'},
  {name: 'FLUORESCENTPINK', pretty_name: 'Fluorescent Pink'},
  {name: 'LIGHTGRAY', pretty_name: 'Light Gray'},
  {name: 'METALLICGOLD', pretty_name: 'Metallic Gold'},
  {name: 'CRIMSON', pretty_name: 'Crimson'},
  {name: 'FLUORESCENTORANGE', pretty_name: 'Fluorescent Orange'},
  {name: 'CORNFLOWER', pretty_name: 'Cornflower'},
  {name: 'SKYBLUE', pretty_name: 'Sky Blue'},
  {name: 'SEABLUE', pretty_name: 'Sea Blue'},
  {name: 'LAKE', pretty_name: 'Lake'},
  {name: 'INDIGO', pretty_name: 'Indigo'},
  {name: 'MIDNIGHT', pretty_name: 'Midnight'},
  {name: 'MIST', pretty_name: 'Mist'},
  {name: 'GRANITE', pretty_name: 'Granite'},
  {name: 'CHARCOAL', pretty_name: 'Charcoal'},
  {name: 'SMOKYTEAL', pretty_name: 'Smoky Teal'},
  {name: 'STEEL', pretty_name: 'Steel'},
  {name: 'SLATE', pretty_name: 'Slate'},
  {name: 'TURQUOISE', pretty_name: 'Turquoise'},
  {name: 'EMERALD', pretty_name: 'Emerald'},
  {name: 'GRASS', pretty_name: 'Grass'},
  {name: 'FOREST', pretty_name: 'Forest'},
  {name: 'SPRUCE', pretty_name: 'Spruce'},
  {name: 'MOSS', pretty_name: 'Moss'},
  {name: 'SEAFOAM', pretty_name: 'Sea Foam'},
  {name: 'KELLYGREEN', pretty_name: 'Kelly Green'},
  {name: 'LIGHTTEAL', pretty_name: 'Light Teal'},
  {name: 'IVY', pretty_name: 'Ivy'},
  {name: 'PINE', pretty_name: 'Pine'},
  {name: 'LAGOON', pretty_name: 'Lagoon'},
  {name: 'VIOLET', pretty_name: 'Violet'},
  {name: 'ORCHID', pretty_name: 'Orchid'},
  {name: 'PLUM', pretty_name: 'Plum'},
  {name: 'RAISIN', pretty_name: 'Raisin'},
  {name: 'GRAPE', pretty_name: 'Grape'},
  {name: 'SCARLET', pretty_name: 'Scarlet'},
  {name: 'TOMATO', pretty_name: 'Tomato'},
  {name: 'CRANBERRY', pretty_name: 'Cranberry'},
  {name: 'MAROON', pretty_name: 'Maroon'},
  {name: 'RASPBERRYRED', pretty_name: 'Raspberry Red'},
  {name: 'BRICK', pretty_name: 'Brick'},
  {name: 'LIGHTLIME', pretty_name: 'Light Lime'},
  {name: 'SUNFLOWER', pretty_name: 'Sunflower'},
  {name: 'MELON', pretty_name: 'Melon'},
  {name: 'APRICOT', pretty_name: 'Apricot'},
  {name: 'PAPRIKA', pretty_name: 'Paprika'},
  {name: 'PUMPKIN', pretty_name: 'Pumpkin'},
  {name: 'BRIGHTOLIVEGREEN', pretty_name: 'Bright Olive Green'},
  {name: 'BRIGHTGOLD', pretty_name: 'Bright Gold'},
  {name: 'COPPER', pretty_name: 'Copper'},
  {name: 'MAHOGANY', pretty_name: 'Mahogany'},
  {name: 'BISQUE', pretty_name: 'Bisque'},
  {name: 'BUBBLEGUM', pretty_name: 'Bubble Gum'},
  {name: 'LIGHTMAUVE', pretty_name: 'Light Mauve'},
  {name: 'DARKMAUVE', pretty_name: 'Dark Mauve'},
  {name: 'WINE', pretty_name: 'Wine'},
  {name: 'GRAY', pretty_name: 'Gray'},
  {name: 'CORAL', pretty_name: 'Coral'},
  {name: 'WHITE', pretty_name: 'White'},
  {name: 'AQUA', pretty_name: 'Aqua'},
  {name: 'MINT', pretty_name: 'Mint'},
  {name: 'CLEARMEDIUM', pretty_name: 'Clear Medium'},
  {name: 'FLUORESCENTYELLOW', pretty_name: 'Fluorescent Yellow'},
  {name: 'FLUORESCENTRED', pretty_name: 'Fluorescent Red'},
  {name: 'FLUORESCENTGREEN', pretty_name: 'Fluorescent Green'}
];
